### ISSUE TITLE
Add soft dependency for the RTAutoSprintEx and ArtificerToggleHover mod

### ISSUE THREAD

**Issue by nit4y** [DrBibop/RoR2VRMod#23]
### I think sprint should be default instead of walking
For us PC players sprint was always the option, I think its the majority of players playing on PC and I think if one want to walk he should press on his left stick instead of the opposite.
Thanks, awesome mod.

**Comment by DrBibop** [comment]
I wanna add the AutoSprint mod as a soft dependency because I have heard that pressing the sprint button isn't easy on some controllers. There are a couple more I also wanna add to the mix. While I do make it a dependency, you could download it here: https://thunderstore.io/package/JohnEdwa/RTAutoSprintEx/
